# FINAL .goreleaser.yml for GitHub Actions
version: 2
project_name: terraform-provider-orcasecurity

builds:
  - id: terraform-provider-orcasecurity
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    ldflags:
      - -s -w

archives:
  - id: terraform-provider-orcasecurity
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    builds:
      - terraform-provider-orcasecurity

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

signs:
  - cmd: gpg
    artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    output: true

release:
  prerelease: auto
