# FINAL .goreleaser.yml
version: 2
project_name: terraform-provider-orcasecurity

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-orcasecurity
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    ldflags:
      - -s -w
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - id: terraform-provider-orcasecurity
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    builds:
      - terraform-provider-orcasecurity

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

signs:
  - cmd: gpg
    args:
      - "--pinentry-mode"
      - "loopback"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    artifacts: checksum
    output: true

release:
  prerelease: auto

changelog:
  skip: true